name = "shared-contact-crm"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "contact-crm-db"
database_id = "17bfd7f3-9e65-4429-a59d-ee56b84b780f"

[vars]
JWT_SECRET = "4q4Bgr40ejlhpwpxVguAM8IQaZennAonFB30iTEpLGG"
